services:
  react-app-1:
    build:
      context: ./react-app-1
      target: ${BUILD_TARGET:-production}
    volumes:
      - app1-build:/app/build
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - app-network

  react-app-2:
    build:
      context: ./react-app-2
      target: ${BUILD_TARGET:-production}
    volumes:
      - app2-build:/app/build
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - app-network

  api:
    build:
      context: ./api
    ports:
      - "${API_PORT:-5000}-${API_PORT_END:-5010}:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=5000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  nginx:
    build: 
      context: ./nginx
      args:
        NGINX_CONF: ${NGINX_CONF:-nginx.conf}
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ${NGINX_CONF_PATH:-./nginx/nginx.conf}:/etc/nginx/conf.d/default.conf
      - ${SSL_CERT_PATH:-./ssl}:/etc/ssl/private:ro
      - app1-build:/usr/share/nginx/html/app1
      - app2-build:/usr/share/nginx/html/app2
    networks:
      - app-network
    depends_on:
      - api
      - react-app-1
      - react-app-2

networks:
  app-network:
    driver: bridge

volumes:
  app1-build:
  app2-build: