services:
  react-app-1:
    build:
      context: ./react-app-1
      dockerfile: Dockerfile
    volumes:
      - app1-build:/app/build
    networks:
      - app-network

  react-app-2:
    build:
      context: ./react-app-2
      dockerfile: Dockerfile
    volumes:
      - app2-build:/app/build
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-5000}-${API_PORT_END:-5010}:5000"
    environment:
      - PORT=5000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - app1-build:/usr/share/nginx/html/app1
      - app2-build:/usr/share/nginx/html/app2
    networks:
      - app-network
    depends_on:
      - api
      - react-app-1
      - react-app-2

networks:
  app-network:
    driver: bridge

volumes:
  app1-build:
  app2-build: