services:
  nginx:
    build: 
      context: ../../nginx
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - app-network
    depends_on:
      api:
        condition: service_healthy
      test-counter:
        condition: service_started
      test-api-client:
        condition: service_started

  api:
    build: 
      context: ../../api
      target: development
    volumes:
      - ../../api:/usr/src/app:delegated
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - EXTERNAL_API_URL=https://jsonplaceholder.typicode.com
      - API_VERSION=1.0.0
      - DEBUG=express:*
    ports:
      - "5001:5000"  # Expose port for debugging - Map container's 5000 to host's 5001 since port 5000 may be in use by macOS ControlCenter
    networks:
      - app-network
    healthcheck:
      test: [
        "CMD-SHELL",
        "wget --spider -q http://localhost:5000/health || (echo 'Health check failed' && exit 1)"
      ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  test-counter:
    build: 
      context: ../../test-counter
      target: development
    ports:
      - "3001:3000"
    volumes:
      - ../../test-counter:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WDS_SOCKET_PORT=80
      - WDS_SOCKET_PATH=/test-counter/ws
      - PUBLIC_URL=/test-counter
      - REACT_APP_API_URL=http://localhost/api
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - GENERATE_SOURCEMAP=true
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || wget -q --spider http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s  # Increased for React dev server startup

  test-api-client:
    build:
      context: ../../test-api-client
      target: development
    ports:
      - "3002:3000"
    volumes:
      - ../../test-api-client:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WDS_SOCKET_PORT=80
      - WDS_SOCKET_PATH=/test-api-client/ws
      - PUBLIC_URL=/test-api-client
      - REACT_APP_API_URL=http://localhost/api
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - GENERATE_SOURCEMAP=true
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || wget -q --spider http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s  # Increased for React dev server startup

networks:
  app-network:
    driver: bridge

