FROM node:18

WORKDIR /usr/src/app

# Add build essentials for native modules
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .
EXPOSE 5000
CMD ["node", "src/index.js"]